### ISSUE TITLE
[Bug] editing react components causes live reloading, but client side rendering different markup from server side

### ISSUE THREAD

**Issue by geekyme** [geekyme/isomorphic-react#1]
When editing my components and saving them, webpack rebuild new assets and the browser live reloaded and displayed the new markup. 

However, I get this in the console: 

"React attempted to use reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server."

**Comment by geekyme** [comment]
Any ideas @sokra @alexaivars ?

**Comment by geekyme** [comment]
No worries I got it figured out. Had to restart my servers using nodemon if i change components otherwise the server side never renders the newly edited components

**Comment by alexaivars** [comment]
I hade the same issue when I started just use  'nodemon --ext js,jsx' and add any extra extensions you need.
